### ISSUE TITLE
Support netty 4

### ISSUE THREAD

**Issue by lleoha** [spotify/netty-zmtp#41]
More like a question than issue. Is support for netty4 planned?

**Comment by noaresare** [comment]
dano is actively working on netty4 support in the branch referenced by https://github.com/spotify/netty-zmtp/pull/37

I'm not sure about the status of the branch, but my guess knowing dano is that it is quite usable already. Feel free to test :)

**Comment by danielnorberg** [comment]
Yeah, merging the netty4 branch is pending some dog-fooding to verify that the api is sane.
