### ISSUE TITLE
A complete example

### ISSUE THREAD

**Issue by whucsfzf** [spotify/netty-zmtp#46]
hello, i have   studied the netty-zmtp,it's perfect. I was wondering can the project provide a complete example?Thank you!

**Comment by danielnorberg** [comment]
See https://github.com/spotify/netty-zmtp/blob/master/src/test/java/com/spotify/netty4/handler/codec/zmtp/EndToEndTest.java#L85:32

**Comment by whucsfzf** [comment]
Thank you . I learned a lot.
